window.QUIZ_DATA = [
  {
    country: "France",
    capital: "Paris",
    continent: "Europe",
    difficulty: "easy",
    fact: "Paris est surnommee la Ville Lumiere pour son role historique culturel et scientifique.",
    hint: "Son drapeau est bleu, blanc, rouge.",
    monument: "Tour Eiffel",
    x: 47,
    y: 34,
  },
  {
    country: "Italie",
    capital: "Rome",
    continent: "Europe",
    difficulty: "easy",
    fact: "Rome possede un patrimoine antique unique et le Vatican au coeur de la ville.",
    hint: "On y deguste souvent pizzas, pates et gelato.",
    monument: "Colisee",
    x: 52,
    y: 41,
  },
  {
    country: "Espagne",
    capital: "Madrid",
    continent: "Europe",
    difficulty: "easy",
    fact: "Madrid abrite le Prado, l'un des musees les plus prestigieux d'Europe.",
    hint: "Ce pays partage la peninsule iberique avec le Portugal.",
    monument: "Sagrada Familia",
    x: 43,
    y: 40,
  },
  {
    country: "Royaume-Uni",
    capital: "Londres",
    continent: "Europe",
    difficulty: "easy",
    fact: "Londres est traversée par la Tamise et celebre pour ses quartiers tres varies.",
    hint: "Ce pays comprend l'Angleterre, l'Ecosse, le Pays de Galles et l'Irlande du Nord.",
    monument: "Big Ben",
    x: 41,
    y: 25,
  },
  {
    country: "Egypte",
    capital: "Le Caire",
    continent: "Afrique",
    difficulty: "easy",
    fact: "Le Caire s'etend pres du Nil et fait face aux pyramides de Gizeh.",
    hint: "Les pyramides et le Nil donnent vite la reponse.",
    monument: "Pyramides de Gizeh",
    x: 57,
    y: 52,
  },
  {
    country: "Kenya",
    capital: "Nairobi",
    continent: "Afrique",
    difficulty: "medium",
    fact: "Nairobi est une capitale rare, bordee d'un parc national avec lions et girafes.",
    hint: "Le pays est connu pour ses safaris et la vallee du Rift.",
    monument: "Parc national d'Amboseli",
    x: 58,
    y: 68,
  },
  {
    country: "Maroc",
    capital: "Rabat",
    continent: "Afrique",
    difficulty: "medium",
    fact: "Rabat est la capitale politique, tandis que Casablanca reste la capitale economique.",
    hint: "Ce pays se situe au nord-ouest de l'Afrique, face a l'Espagne.",
    monument: "Mosquee Hassan II",
    x: 40,
    y: 46,
  },
  {
    country: "Afrique du Sud",
    capital: "Pretoria",
    continent: "Afrique",
    difficulty: "hard",
    fact: "L'Afrique du Sud possede trois capitales institutionnelles selon les pouvoirs.",
    hint: "Le pays touche deux oceans a l'extreme sud du continent.",
    monument: "Table Mountain",
    x: 54,
    y: 88,
  },
  {
    country: "Japon",
    capital: "Tokyo",
    continent: "Asie",
    difficulty: "easy",
    fact: "Tokyo est l'une des plus grandes agglomerations du monde et un centre technologique majeur.",
    hint: "Ce pays est un archipel a l'est de la Coree et de la Chine.",
    monument: "Mont Fuji",
    x: 82,
    y: 39,
  },
  {
    country: "Inde",
    capital: "New Delhi",
    continent: "Asie",
    difficulty: "easy",
    fact: "New Delhi est integree a la vaste megaville de Delhi, au nord du pays.",
    hint: "Le Taj Mahal est dans ce pays, mais pas dans sa capitale.",
    monument: "Taj Mahal",
    x: 67,
    y: 56,
  },
  {
    country: "Thaïlande",
    capital: "Bangkok",
    continent: "Asie",
    difficulty: "medium",
    fact: "Bangkok est celebre pour ses canaux, ses temples et son nom ceremonial tres long.",
    hint: "Le pays est repute pour ses plages et ses temples dores.",
    monument: "Wat Arun",
    x: 73,
    y: 62,
  },
  {
    country: "Kazakhstan",
    capital: "Astana",
    continent: "Asie",
    difficulty: "hard",
    fact: "Astana a change plusieurs fois de nom au fil des evolutions politiques recentes.",
    hint: "C'est le plus grand pays enclavé du monde.",
    monument: "Tour Bayterek",
    x: 65,
    y: 35,
  },
  {
    country: "Canada",
    capital: "Ottawa",
    continent: "Amérique du Nord",
    difficulty: "easy",
    fact: "Ottawa se situe entre Toronto et Montreal, sur la riviere des Outaouais.",
    hint: "Le pays est connu pour sa feuille d'erable.",
    monument: "Chutes du Niagara",
    x: 24,
    y: 25,
  },
  {
    country: "Mexique",
    capital: "Mexico",
    continent: "Amérique du Nord",
    difficulty: "medium",
    fact: "Mexico est batie sur l'ancien site de Tenochtitlan, la cite aztèque.",
    hint: "Le pays relie l'Amerique du Nord a l'Amerique centrale.",
    monument: "Chichen Itza",
    x: 18,
    y: 49,
  },
  {
    country: "Costa Rica",
    capital: "San Jose",
    continent: "Amérique du Nord",
    difficulty: "hard",
    fact: "Le Costa Rica n'a pas d'armee permanente depuis 1948.",
    hint: "Ce petit pays est celebre pour sa biodiversite et ses volcans.",
    monument: "Volcan Arenal",
    x: 21,
    y: 58,
  },
  {
    country: "Brésil",
    capital: "Brasilia",
    continent: "Amérique du Sud",
    difficulty: "easy",
    fact: "Brasilia a ete construite au XXe siecle pour developper l'interieur du pays.",
    hint: "Le pays parle portugais et abrite l'Amazonie.",
    monument: "Christ Redempteur",
    x: 31,
    y: 76,
  },
  {
    country: "Pérou",
    capital: "Lima",
    continent: "Amérique du Sud",
    difficulty: "medium",
    fact: "Lima domine la cote pacifique et constitue la principale porte d'entree vers le pays.",
    hint: "Le Machu Picchu se situe dans ce pays andin.",
    monument: "Machu Picchu",
    x: 23,
    y: 73,
  },
  {
    country: "Argentine",
    capital: "Buenos Aires",
    continent: "Amérique du Sud",
    difficulty: "medium",
    fact: "Buenos Aires est souvent associee au tango et a une forte influence europeenne.",
    hint: "Le pays partage une longue frontiere avec le Chili.",
    monument: "Obelisque de Buenos Aires",
    x: 29,
    y: 89,
  },
  {
    country: "Australie",
    capital: "Canberra",
    continent: "Océanie",
    difficulty: "easy",
    fact: "Canberra a ete choisie pour departager Sydney et Melbourne.",
    hint: "Ce pays-continent est entoure d'oceans.",
    monument: "Opera de Sydney",
    x: 84,
    y: 82,
  },
  {
    country: "Nouvelle-Zélande",
    capital: "Wellington",
    continent: "Océanie",
    difficulty: "medium",
    fact: "Wellington est l'une des capitales les plus ventees du monde.",
    hint: "Le pays est compose de deux grandes iles au sud-est de l'Australie.",
    monument: "Milford Sound",
    x: 92,
    y: 90,
  },
  {
    country: "Fidji",
    capital: "Suva",
    continent: "Océanie",
    difficulty: "hard",
    fact: "Suva est situee sur l'ile de Viti Levu, au coeur du Pacifique sud.",
    hint: "Cet archipel du Pacifique est connu pour ses lagons et recifs.",
    monument: "Jardin du Geant endormi",
    x: 89,
    y: 71,
  },
  {
    country: "Turquie",
    capital: "Ankara",
    continent: "Asie",
    difficulty: "medium",
    fact: "Ankara est la capitale administrative, tandis qu'Istanbul reste la metropole la plus celebre.",
    hint: "Ce pays s'etend entre Europe et Asie.",
    monument: "Sainte-Sophie",
    x: 56,
    y: 41,
  },
  {
    country: "Islande",
    capital: "Reykjavik",
    continent: "Europe",
    difficulty: "hard",
    fact: "Reykjavik est la capitale souveraine la plus septentrionale du monde.",
    hint: "Ce pays volcanique est situe dans l'Atlantique nord.",
    monument: "Blue Lagoon",
    x: 28,
    y: 16,
  },
];