window.QUIZ_DATA = [
  {
    country: "France",
    capital: "Paris",
    continent: "Europe",
    difficulty: "easy",
    fact: "Paris est surnommee la Ville Lumiere pour son role historique culturel et scientifique.",
    hint: "Son drapeau est bleu, blanc, rouge.",
    monument: "Tour Eiffel",
    x: 47,
    y: 34,
  },
  {
    country: "Italie",
    capital: "Rome",
    continent: "Europe",
    difficulty: "easy",
    fact: "Rome possede un patrimoine antique unique et le Vatican au coeur de la ville.",
    hint: "On y deguste souvent pizzas, pates et gelato.",
    monument: "Colisee",
    x: 52,
    y: 41,
  },
  {
    country: "Espagne",
    capital: "Madrid",
    continent: "Europe",
    difficulty: "easy",
    fact: "Madrid abrite le Prado, l'un des musees les plus prestigieux d'Europe.",
    hint: "Ce pays partage la peninsule iberique avec le Portugal.",
    monument: "Sagrada Familia",
    x: 43,
    y: 40,
  },
  {
    country: "Royaume-Uni",
    capital: "Londres",
    continent: "Europe",
    difficulty: "easy",
    fact: "Londres est traversée par la Tamise et celebre pour ses quartiers tres varies.",
    hint: "Ce pays comprend l'Angleterre, l'Ecosse, le Pays de Galles et l'Irlande du Nord.",
    monument: "Big Ben",
    x: 41,
    y: 25,
  },
  {
    country: "Egypte",
    capital: "Le Caire",
    continent: "Afrique",
    difficulty: "easy",
    fact: "Le Caire s'etend pres du Nil et fait face aux pyramides de Gizeh.",
    hint: "Les pyramides et le Nil donnent vite la reponse.",
    monument: "Pyramides de Gizeh",
    x: 57,
    y: 52,
  },
  {
    country: "Kenya",
    capital: "Nairobi",
    continent: "Afrique",
    difficulty: "medium",
    fact: "Nairobi est une capitale rare, bordee d'un parc national avec lions et girafes.",
    hint: "Le pays est connu pour ses safaris et la vallee du Rift.",
    monument: "Parc national d'Amboseli",
    x: 58,
    y: 68,
  },
  {
    country: "Maroc",
    capital: "Rabat",
    continent: "Afrique",
    difficulty: "medium",
    fact: "Rabat est la capitale politique, tandis que Casablanca reste la capitale economique.",
    hint: "Ce pays se situe au nord-ouest de l'Afrique, face a l'Espagne.",
    monument: "Mosquee Hassan II",
    x: 40,
    y: 46,
  },
  {
    country: "Afrique du Sud",
    capital: "Pretoria",
    continent: "Afrique",
    difficulty: "hard",
    fact: "L'Afrique du Sud possede trois capitales institutionnelles selon les pouvoirs.",
    hint: "Le pays touche deux oceans a l'extreme sud du continent.",
    monument: "Table Mountain",
    x: 54,
    y: 88,
  },
  {
    country: "Japon",
    capital: "Tokyo",
    continent: "Asie",
    difficulty: "easy",
    fact: "Tokyo est l'une des plus grandes agglomerations du monde et un centre technologique majeur.",
    hint: "Ce pays est un archipel a l'est de la Coree et de la Chine.",
    monument: "Mont Fuji",
    x: 82,
    y: 39,
  },
  {
    country: "Inde",
    capital: "New Delhi",
    continent: "Asie",
    difficulty: "easy",
    fact: "New Delhi est integree a la vaste megaville de Delhi, au nord du pays.",
    hint: "Le Taj Mahal est dans ce pays, mais pas dans sa capitale.",
    monument: "Taj Mahal",
    x: 67,
    y: 56,
  },
  {
    country: "Thaïlande",
    capital: "Bangkok",
    continent: "Asie",
    difficulty: "medium",
    fact: "Bangkok est celebre pour ses canaux, ses temples et son nom ceremonial tres long.",
    hint: "Le pays est repute pour ses plages et ses temples dores.",
    monument: "Wat Arun",
    x: 73,
    y: 62,
  },
  {
    country: "Kazakhstan",
    capital: "Astana",
    continent: "Asie",
    difficulty: "hard",
    fact: "Astana a change plusieurs fois de nom au fil des evolutions politiques recentes.",
    hint: "C'est le plus grand pays enclavé du monde.",
    monument: "Tour Bayterek",
    x: 65,
    y: 35,
  },
  {
    country: "Canada",
    capital: "Ottawa",
    continent: "Amérique du Nord",
    difficulty: "easy",
    fact: "Ottawa se situe entre Toronto et Montreal, sur la riviere des Outaouais.",
    hint: "Le pays est connu pour sa feuille d'erable.",
    monument: "Chutes du Niagara",
    x: 24,
    y: 25,
  },
  {
    country: "Mexique",
    capital: "Mexico",
    continent: "Amérique du Nord",
    difficulty: "medium",
    fact: "Mexico est batie sur l'ancien site de Tenochtitlan, la cite aztèque.",
    hint: "Le pays relie l'Amerique du Nord a l'Amerique centrale.",
    monument: "Chichen Itza",
    x: 18,
    y: 49,
  },
  {
    country: "Costa Rica",
    capital: "San Jose",
    continent: "Amérique du Nord",
    difficulty: "hard",
    fact: "Le Costa Rica n'a pas d'armee permanente depuis 1948.",
    hint: "Ce petit pays est celebre pour sa biodiversite et ses volcans.",
    monument: "Volcan Arenal",
    x: 21,
    y: 58,
  },
  {
    country: "Brésil",
    capital: "Brasilia",
    continent: "Amérique du Sud",
    difficulty: "easy",
    fact: "Brasilia a ete construite au XXe siecle pour developper l'interieur du pays.",
    hint: "Le pays parle portugais et abrite l'Amazonie.",
    monument: "Christ Redempteur",
    x: 31,
    y: 76,
  },
  {
    country: "Pérou",
    capital: "Lima",
    continent: "Amérique du Sud",
    difficulty: "medium",
    fact: "Lima domine la cote pacifique et constitue la principale porte d'entree vers le pays.",
    hint: "Le Machu Picchu se situe dans ce pays andin.",
    monument: "Machu Picchu",
    x: 23,
    y: 73,
  },
  {
    country: "Argentine",
    capital: "Buenos Aires",
    continent: "Amérique du Sud",
    difficulty: "medium",
    fact: "Buenos Aires est souvent associee au tango et a une forte influence europeenne.",
    hint: "Le pays partage une longue frontiere avec le Chili.",
    monument: "Obelisque de Buenos Aires",
    x: 29,
    y: 89,
  },
  {
    country: "Australie",
    capital: "Canberra",
    continent: "Océanie",
    difficulty: "easy",
    fact: "Canberra a ete choisie pour departager Sydney et Melbourne.",
    hint: "Ce pays-continent est entoure d'oceans.",
    monument: "Opera de Sydney",
    x: 84,
    y: 82,
  },
  {
    country: "Nouvelle-Zélande",
    capital: "Wellington",
    continent: "Océanie",
    difficulty: "medium",
    fact: "Wellington est l'une des capitales les plus ventees du monde.",
    hint: "Le pays est compose de deux grandes iles au sud-est de l'Australie.",
    monument: "Milford Sound",
    x: 92,
    y: 90,
  },
  {
    country: "Fidji",
    capital: "Suva",
    continent: "Océanie",
    difficulty: "hard",
    fact: "Suva est situee sur l'ile de Viti Levu, au coeur du Pacifique sud.",
    hint: "Cet archipel du Pacifique est connu pour ses lagons et recifs.",
    monument: "Jardin du Geant endormi",
    x: 89,
    y: 71,
  },
  {
    country: "Turquie",
    capital: "Ankara",
    continent: "Asie",
    difficulty: "medium",
    fact: "Ankara est la capitale administrative, tandis qu'Istanbul reste la metropole la plus celebre.",
    hint: "Ce pays s'etend entre Europe et Asie.",
    monument: "Sainte-Sophie",
    x: 56,
    y: 41,
  },
  {
    country: "Islande",
    capital: "Reykjavik",
    continent: "Europe",
    difficulty: "hard",
    fact: "Reykjavik est la capitale souveraine la plus septentrionale du monde.",
    hint: "Ce pays volcanique est situe dans l'Atlantique nord.",
    monument: "Blue Lagoon",
    x: 28,
    y: 16,
  },
  {
    country: "Allemagne",
    capital: "Berlin",
    continent: "Europe",
    difficulty: "easy",
    fact: "Berlin est connue pour sa scene culturelle et son histoire liee au Mur de Berlin.",
    hint: "Ce pays est au coeur de l'Europe et a pour symbole l'aigle noir.",
    monument: "Porte de Brandebourg",
    x: 50,
    y: 28,
  },
  {
    country: "Portugal",
    capital: "Lisbonne",
    continent: "Europe",
    difficulty: "medium",
    fact: "Lisbonne est batie sur plusieurs collines au bord du Tage.",
    hint: "Ce pays occupe la facade ouest de la peninsule iberique.",
    monument: "Tour de Belem",
    x: 38,
    y: 42,
  },
  {
    country: "Grèce",
    capital: "Athènes",
    continent: "Europe",
    difficulty: "medium",
    fact: "Athenes est souvent consideree comme le berceau de la democratie antique.",
    hint: "L'Acropole y domine la ville.",
    monument: "Parthenon",
    x: 57,
    y: 43,
  },
  {
    country: "Sénégal",
    capital: "Dakar",
    continent: "Afrique",
    difficulty: "easy",
    fact: "Dakar se trouve sur la presqu'ile du Cap-Vert, a l'ouest du continent africain.",
    hint: "Ce pays est celebre pour le lac Rose et la musique mbalax.",
    monument: "Monument de la Renaissance africaine",
    x: 31,
    y: 53,
  },
  {
    country: "Nigéria",
    capital: "Abuja",
    continent: "Afrique",
    difficulty: "medium",
    fact: "Abuja a ete choisie pour sa position centrale dans le pays.",
    hint: "C'est le pays le plus peuple d'Afrique.",
    monument: "Aso Rock",
    x: 49,
    y: 60,
  },
  {
    country: "Tanzanie",
    capital: "Dodoma",
    continent: "Afrique",
    difficulty: "hard",
    fact: "Dodoma partage les fonctions administratives avec Dar es Salaam dans la pratique.",
    hint: "Le Kilimandjaro se trouve dans ce pays.",
    monument: "Kilimandjaro",
    x: 59,
    y: 71,
  },
  {
    country: "Chine",
    capital: "Pekin",
    continent: "Asie",
    difficulty: "easy",
    fact: "Pekin abrite la Cite interdite et de vastes sites historiques imperiaux.",
    hint: "La Grande Muraille est dans ce pays.",
    monument: "Cite interdite",
    x: 76,
    y: 34,
  },
  {
    country: "Corée du Sud",
    capital: "Seoul",
    continent: "Asie",
    difficulty: "medium",
    fact: "Seoul est un centre majeur de technologie, de design et de culture pop.",
    hint: "Ce pays partage sa peninsule avec un voisin du Nord.",
    monument: "Palais Gyeongbokgung",
    x: 80,
    y: 37,
  },
  {
    country: "Vietnam",
    capital: "Hanoi",
    continent: "Asie",
    difficulty: "medium",
    fact: "Hanoi melange architecture coloniale, lacs urbains et vieux quartiers animes.",
    hint: "La baie d'Ha Long attire de nombreux voyageurs dans ce pays.",
    monument: "Baie d'Ha Long",
    x: 74,
    y: 58,
  },
  {
    country: "États-Unis",
    capital: "Washington",
    continent: "Amérique du Nord",
    difficulty: "easy",
    fact: "Washington est un district federal distinct des Etats qui l'entourent.",
    hint: "La Statue de la Liberte se trouve dans ce pays, mais pas dans sa capitale.",
    monument: "Grand Canyon",
    x: 15,
    y: 33,
  },
  {
    country: "Cuba",
    capital: "La Havane",
    continent: "Amérique du Nord",
    difficulty: "medium",
    fact: "La Havane est fameuse pour son front de mer, le Malecon, et ses voitures anciennes.",
    hint: "Cette ile des Caraibes se situe au sud de la Floride.",
    monument: "Capitole de La Havane",
    x: 22,
    y: 46,
  },
  {
    country: "Guatemala",
    capital: "Guatemala",
    continent: "Amérique du Nord",
    difficulty: "hard",
    fact: "La capitale porte le meme nom que le pays dans sa forme courte courante.",
    hint: "Ce pays d'Amerique centrale possede de nombreux sites mayas.",
    monument: "Tikal",
    x: 19,
    y: 54,
  },
  {
    country: "Chili",
    capital: "Santiago",
    continent: "Amérique du Sud",
    difficulty: "easy",
    fact: "Santiago est encadree par la cordillere des Andes et la chaine cotiere.",
    hint: "Ce pays forme une longue bande entre Pacifique et Andes.",
    monument: "Desert d'Atacama",
    x: 22,
    y: 86,
  },
  {
    country: "Colombie",
    capital: "Bogota",
    continent: "Amérique du Sud",
    difficulty: "medium",
    fact: "Bogota se situe a haute altitude sur un plateau andin.",
    hint: "Le cafe et Carthagene evoquent souvent ce pays.",
    monument: "Carthagene des Indes",
    x: 24,
    y: 63,
  },
  {
    country: "Équateur",
    capital: "Quito",
    continent: "Amérique du Sud",
    difficulty: "hard",
    fact: "Quito est proche de l'equateur et s'etend dans une vallee andine.",
    hint: "Les iles Galapagos appartiennent a ce pays.",
    monument: "Mitad del Mundo",
    x: 22,
    y: 67,
  },
  {
    country: "Papouasie-Nouvelle-Guinée",
    capital: "Port Moresby",
    continent: "Océanie",
    difficulty: "hard",
    fact: "Port Moresby se trouve au sud-est de la grande ile de Nouvelle-Guinee.",
    hint: "Ce pays partage une grande ile avec l'Indonesie.",
    monument: "Sentier Kokoda",
    x: 86,
    y: 74,
  },
  {
    country: "Samoa",
    capital: "Apia",
    continent: "Océanie",
    difficulty: "medium",
    fact: "Apia est la principale ville de l'ile d'Upolu dans le Pacifique.",
    hint: "Cet Etat insulaire du Pacifique est connu pour sa culture polynesienne.",
    monument: "To-Sua Ocean Trench",
    x: 93,
    y: 73,
  },
  {
    country: "Vanuatu",
    capital: "Port-Vila",
    continent: "Océanie",
    difficulty: "hard",
    fact: "Port-Vila est la capitale d'un archipel volcanique au nord-est de l'Australie.",
    hint: "Ce pays est celebre pour ses volcans actifs et ses villages melanesiens.",
    monument: "Mont Yasur",
    x: 91,
    y: 79,
  },
  {
    country: "Suisse",
    capital: "Berne",
    continent: "Europe",
    difficulty: "medium",
    fact: "Berne est la ville federale de la Suisse, tandis que Zurich reste le principal centre economique.",
    hint: "Ce pays alpin est celebre pour ses montagnes, ses montres et son chocolat.",
    monument: "Cervin",
    x: 49,
    y: 35,
  },
  {
    country: "Norvège",
    capital: "Oslo",
    continent: "Europe",
    difficulty: "medium",
    fact: "Oslo combine fjords, design nordique et une forte proximite avec la nature.",
    hint: "Les fjords et le soleil de minuit orientent vite vers ce pays.",
    monument: "Fjords norvégiens",
    x: 50,
    y: 18,
  },
  {
    country: "Pologne",
    capital: "Varsovie",
    continent: "Europe",
    difficulty: "medium",
    fact: "Varsovie a ete largement reconstruite apres la Seconde Guerre mondiale.",
    hint: "Ce pays d'Europe centrale a Cracovie parmi ses villes les plus connues.",
    monument: "Château de Wawel",
    x: 56,
    y: 29,
  },
  {
    country: "Algérie",
    capital: "Alger",
    continent: "Afrique",
    difficulty: "easy",
    fact: "Alger regarde la Mediterranee et se distingue par sa Casbah historique.",
    hint: "C'est le plus vaste pays d'Afrique en superficie.",
    monument: "Casbah d'Alger",
    x: 45,
    y: 46,
  },
  {
    country: "Ghana",
    capital: "Accra",
    continent: "Afrique",
    difficulty: "medium",
    fact: "Accra est une grande ville cotiere dynamique du golfe de Guinee.",
    hint: "Le fort de Cape Coast et le cacao font penser a ce pays.",
    monument: "Cape Coast Castle",
    x: 45,
    y: 61,
  },
  {
    country: "Madagascar",
    capital: "Antananarivo",
    continent: "Afrique",
    difficulty: "hard",
    fact: "Antananarivo se trouve sur les hautes terres de cette grande ile de l'ocean Indien.",
    hint: "Ce pays insulaire est celebre pour ses lemuriens.",
    monument: "Avenue des Baobabs",
    x: 65,
    y: 79,
  },
  {
    country: "Arabie saoudite",
    capital: "Riyad",
    continent: "Asie",
    difficulty: "medium",
    fact: "Riyad est au coeur de la peninsule Arabique et connait un essor urbain rapide.",
    hint: "La Mecque et Medine se trouvent dans ce pays.",
    monument: "Al-Ula",
    x: 61,
    y: 52,
  },
  {
    country: "Indonésie",
    capital: "Jakarta",
    continent: "Asie",
    difficulty: "easy",
    fact: "Jakarta est l'une des plus vastes agglomerations d'Asie du Sud-Est.",
    hint: "Bali fait partie de cet immense archipel.",
    monument: "Borobudur",
    x: 79,
    y: 70,
  },
  {
    country: "Philippines",
    capital: "Manille",
    continent: "Asie",
    difficulty: "medium",
    fact: "Manille s'etend dans une vaste baie sur l'ile de Luçon.",
    hint: "Cet archipel d'Asie du Sud-Est compte plus de 7000 iles.",
    monument: "Rizieres de Banaue",
    x: 83,
    y: 58,
  },
  {
    country: "Panama",
    capital: "Panama",
    continent: "Amérique du Nord",
    difficulty: "medium",
    fact: "La capitale Panama se trouve a l'entree pacifique du celebre canal.",
    hint: "Le canal maritime mondialement connu traverse ce pays.",
    monument: "Canal de Panama",
    x: 21,
    y: 60,
  },
  {
    country: "Jamaïque",
    capital: "Kingston",
    continent: "Amérique du Nord",
    difficulty: "medium",
    fact: "Kingston est la grande ville portuaire du sud-est de l'ile.",
    hint: "Le reggae et Bob Marley evoquent souvent ce pays.",
    monument: "Dunn's River Falls",
    x: 23,
    y: 47,
  },
  {
    country: "Bolivie",
    capital: "Sucre",
    continent: "Amérique du Sud",
    difficulty: "hard",
    fact: "La Bolivie partage ses fonctions politiques entre Sucre et La Paz selon les institutions.",
    hint: "Le salar d'Uyuni est dans ce pays andin.",
    monument: "Salar d'Uyuni",
    x: 27,
    y: 76,
  },
  {
    country: "Uruguay",
    capital: "Montevideo",
    continent: "Amérique du Sud",
    difficulty: "medium",
    fact: "Montevideo se situe sur l'estuaire du Rio de la Plata face a Buenos Aires.",
    hint: "Ce petit pays est place entre le Bresil et l'Argentine.",
    monument: "Palacio Salvo",
    x: 31,
    y: 88,
  },
  {
    country: "Paraguay",
    capital: "Asuncion",
    continent: "Amérique du Sud",
    difficulty: "hard",
    fact: "Asuncion est l'une des plus anciennes villes d'Amerique du Sud encore habitees.",
    hint: "Ce pays est enclavé entre Bresil, Argentine et Bolivie.",
    monument: "Ruines jesuites de Trinidad",
    x: 29,
    y: 80,
  },
  {
    country: "Tonga",
    capital: "Nuku'alofa",
    continent: "Océanie",
    difficulty: "hard",
    fact: "Nuku'alofa est la capitale royale de cet archipel polynesien du Pacifique.",
    hint: "C'est un royaume insulaire du Pacifique sud.",
    monument: "Mapu'a 'a Vaea",
    x: 95,
    y: 82,
  },
  {
    country: "Îles Salomon",
    capital: "Honiara",
    continent: "Océanie",
    difficulty: "hard",
    fact: "Honiara est située sur l'ile de Guadalcanal dans le Pacifique sud-ouest.",
    hint: "Cet Etat melanesien est a l'est de la Papouasie-Nouvelle-Guinee.",
    monument: "Mataniko Falls",
    x: 92,
    y: 77,
  },
];